In [2]:
import pandas as pd
import nltk
from bs4 import BeautifulSoup
from nltk.tokenize import RegexpTokenizer
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.probability import FreqDist
import numpy as np
from sklearn.feature_extraction.text import  TfidfTransformer
from IPython.display import Image

%pylab inline

bd=pd.read_csv('sentemental_dataset_kaggle.tsv',sep='\t')

Populating the interactive namespace from numpy and matplotlib


In [17]:
cv = CountVectorizer(vocabulary=['hot', 'cold', 'old'])
cv.fit_transform(['pease porridge hot hot', 'pease porridge cold', 'pease porridge in the pot',
                  'nine days old']).toarray()

array([[2, 0, 0],
       [0, 1, 0],
       [0, 0, 0],
       [0, 0, 1]], dtype=int64)

In [16]:
from sklearn.feature_extraction.text import CountVectorizer

allvoc=''
#set(bd_xy.iloc[:,1].values)
for i in tokens_stem:
    allvoc=allvoc+i+' '
vocab = [allvoc]
vec = CountVectorizer().fit(vocab)

#print len(vec.get_feature_names())

ar=[]

for vi in tokens_stem:
    sentence = vec.transform([vi])
    r=sentence.toarray() 
    rr=r[0]
    ar.append(rr)
    
arrr=np.array(ar)    

In [17]:
len(vec.get_feature_names())

158

In [24]:
arrr[3,:]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [18]:
X=np.array([[1,2,3,4],[0,1,2,3],[0,2,0,0]])
print X

[[1 2 3 4]
 [0 1 2 3]
 [0 2 0 0]]


Transform a count matrix to a normalized tf or tf-idf representation
Tf means term-frequency while tf-idf means term-frequency times inverse document-frequency. This is a common term weighting scheme in information retrieval, that has also found good use in document classification.
The goal of using tf-idf instead of the raw frequencies of occurrence of a token in a given document is to scale down the impact of tokens that occur very frequently in a given corpus and that are hence empirically less informative than features that occur in a small fraction of the training corpus.
The actual formula used for tf-idf is tf * (idf + 1) = tf + tf * idf, instead of tf * idf. The effect of this is that terms with zero idf, i.e. that occur in all documents of a training set, will not be entirely ignored. The formulas used to compute tf and idf depend on parameter settings that correspond to the SMART notation used in IR, as follows:

In [19]:
vectorizer = TfidfTransformer()
X_out = vectorizer.fit_transform(X)
X_out.toarray()


array([[ 0.24357449,  0.28771804,  0.55573404,  0.74097872],
       [ 0.        ,  0.21055839,  0.54226453,  0.81339679],
       [ 0.        ,  1.        ,  0.        ,  0.        ]])